name: NodeJS with Webpack

on:
  push:
    branches: [ "hexo" ]
  pull_request:
    branches: [ "hexo" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.17]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm install -g hexo@3.9.0
        hexo g
